FROM golang:1.18

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		docker.io; \
	apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
	rm -rf /var/lib/apt/lists/* 

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

ENV DOCKER_API_VERSION=1.39

CMD ["./app"]
