version: "3"
services:
  app:
    image: 'riobueno/php-apache:7.2'
    volumes:
      - ./SITE:/var/www/html
    restart: unless-stopped
    ports: 
      - "8000:80"

  DB:
    image: 'mysql:5.7'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - TZ=America/Lima
    volumes:
      - ./d-mysql:/var/lib/mysql
#    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flus$
    ports:
      - "3304:3306"
